import React from 'react';
import { Ionicons, Feather, MaterialCommunityIcons } from '@expo/vector-icons';

export const Icon = {
  logo: (props: any) => <MaterialCommunityIcons name="pen-plus" {...props} />,
  write: (props: any) => <Feather name="edit-3" {...props} />,
  edit: (props: any) => <Feather name="edit-3" {...props} />,
  chat: (props: any) => <Ionicons name="chatbubble-ellipses-outline" {...props} />,
  settings: (props: any) => <Ionicons name="settings-outline" {...props} />,
  back: (props: any) => <Ionicons name="chevron-back" {...props} />,
  forward: (props: any) => <Ionicons name="chevron-forward" {...props} />,
  add: (props: any) => <Feather name="plus" {...props} />,
  delete: (props: any) => <Feather name="trash-2" {...props} />,
  trash: (props: any) => <Feather name="trash-2" {...props} />,
  save: (props: any) => <Feather name="download" {...props} />,
  search: (props: any) => <Feather name="search" {...props} />,
  star: (props: any) => <Ionicons name="star" {...props} />,
  book: (props: any) => <Ionicons name="book-outline" {...props} />,
  chapter: (props: any) => <MaterialCommunityIcons name="text-box-outline" {...props} />,
  character: (props: any) => <Ionicons name="person-outline" {...props} />,
  idea: (props: any) => <Ionicons name="bulb-outline" {...props} />,
  stats: (props: any) => <Feather name="bar-chart-2" {...props} />,
  export: (props: any) => <Feather name="share" {...props} />,
  backup: (props: any) => <Ionicons name="cloud-upload-outline" {...props} />,
  test: (props: any) => <Feather name="zap" {...props} />,
  thinking: (props: any) => <MaterialCommunityIcons name="brain" {...props} />,
  loading: (props: any) => <Ionicons name="sync-outline" {...props} />,
  check: (props: any) => <Ionicons name="checkmark" {...props} />,
  close: (props: any) => <Feather name="x" {...props} />,
  arrow: (props: any) => <Feather name="arrow-up" {...props} />,
  send: (props: any) => <Ionicons name="send" {...props} />,
  autoWrite: (props: any) => <MaterialCommunityIcons name="auto-fix" {...props} />,
  auto: (props: any) => <MaterialCommunityIcons name="auto-fix" {...props} />,
  continueWrite: (props: any) => <Feather name="skip-forward" {...props} />,
  newChapter: (props: any) => <Feather name="file-plus" {...props} />,
  outline: (props: any) => <MaterialCommunityIcons name="format-list-bulleted" {...props} />,
  preview: (props: any) => <MaterialCommunityIcons name="eye-outline" {...props} />,
  modify: (props: any) => <Feather name="edit" {...props} />,
  tts: (props: any) => <Ionicons name="volume-high-outline" {...props} />,
  copy: (props: any) => <Feather name="copy" {...props} />,
  image: (props: any) => <Feather name="image" {...props} />,
  menu: (props: any) => <Feather name="menu" {...props} />,
  more: (props: any) => <Feather name="more-horizontal" {...props} />,
  down: (props: any) => <Ionicons name="chevron-down" {...props} />,
  up: (props: any) => <Ionicons name="chevron-up" {...props} />,
};
