import React from 'react';
import {
  ButtIcon, PenisIcon, BreastIcon, LegsIcon, LipsIcon,
  FireIcon, HeartIcon, RoseIcon, BookIcon, PenIcon,
  GearIcon, UserIcon, SearchIcon, SendArrowIcon,
  BackIcon, ForwardIcon, DownIcon, CloseIcon, CheckIcon,
  PlusIcon, TrashIcon, SaveIcon, BrainIcon, DotsVerticalIcon,
} from '../components/icons/AdultIcons';

const C = '#C77D8A';

const make = (Comp: React.FC<any>) => (props: any) => <Comp {...props} color={props.color || C} />;

export const Icon = {
  logo: make(HeartIcon),
  write: make(PenIcon),
  edit: make(PenIcon),
  chat: make(LipsIcon),
  settings: make(GearIcon),
  back: make(BackIcon),
  forward: make(ForwardIcon),
  add: make(PlusIcon),
  delete: make(TrashIcon),
  trash: make(TrashIcon),
  save: make(SaveIcon),
  search: make(SearchIcon),
  star: make(HeartIcon),
  book: make(BookIcon),
  chapter: make(BookIcon),
  character: make(UserIcon),
  idea: make(FireIcon),
  stats: make(FireIcon),
  export: make(SaveIcon),
  backup: make(SaveIcon),
  test: make(FireIcon),
  thinking: make(BrainIcon),
  loading: make(FireIcon),
  check: make(CheckIcon),
  close: make(CloseIcon),
  arrow: make(SendArrowIcon),
  send: make(SendArrowIcon),
  autoWrite: make(PenIcon),
  auto: make(PenIcon),
  continueWrite: make(ForwardIcon),
  newChapter: make(PlusIcon),
  outline: make(BookIcon),
  preview: make(HeartIcon),
  modify: make(PenIcon),
  tts: make(FireIcon),
  copy: make(SaveIcon),
  image: make(HeartIcon),
  menu: make(PlusIcon),
  more: make(DotsVerticalIcon),
  down: make(DownIcon),
  up: make(ForwardIcon),
  heart: make(HeartIcon),
  fire: make(FireIcon),
  rose: make(RoseIcon),
  kiss: make(LipsIcon),
  lock: make(CloseIcon),
  adult: make(BreastIcon),
  butt: make(ButtIcon),
  penis: make(PenisIcon),
  breast: make(BreastIcon),
  legs: make(LegsIcon),
  lips: make(LipsIcon),
};
