import { StyleSheet, StatusBar } from 'react-native';
import { T } from '../lib/theme';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: T.bg },
  header: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingHorizontal: 18, paddingTop: (StatusBar.currentHeight || 44) + 6, paddingBottom: 14,
  },
  headerTitle: { flex: 1 },
  brand: { fontSize: 26, lineHeight: 31, fontWeight: '900', color: T.text, letterSpacing: 2 },
  subline: { marginTop: 2, fontSize: 11, color: T.textMuted },
  headerButton: {
    height: 36, borderRadius: 18, paddingHorizontal: 13,
    backgroundColor: T.card, borderWidth: 1, borderColor: T.border,
    flexDirection: 'row', alignItems: 'center', gap: 5,
  },
  headerButtonText: { color: T.text, fontSize: 12, fontWeight: '700' },
  iconButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: T.card, borderWidth: 1, borderColor: T.border, alignItems: 'center', justifyContent: 'center' },
  searchBar: {
    minHeight: 48, maxHeight: 120, marginHorizontal: 16, borderRadius: 24,
    backgroundColor: T.surface, borderWidth: 1, borderColor: T.borderLight,
    flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 15, paddingVertical: 9,
  },
  input: { flex: 1, minHeight: 28, color: T.text, fontSize: 15, textAlignVertical: 'center', paddingVertical: 0 },
  searchButton: { height: 32, borderRadius: 16, paddingHorizontal: 14, backgroundColor: '#E7E7E7', alignItems: 'center', justifyContent: 'center' },
  searchButtonText: { color: '#111', fontSize: 12, fontWeight: '800' },
  clearButton: { height: 30, borderRadius: 15, paddingHorizontal: 9, justifyContent: 'center', backgroundColor: '#222' },
  clearText: { color: T.textSec, fontSize: 11 },
  categories: { flexDirection: 'row', gap: 7, paddingHorizontal: 16, marginTop: 12, flexWrap: 'wrap' },
  categoryChip: { minHeight: 31, borderRadius: 16, paddingHorizontal: 12, justifyContent: 'center', backgroundColor: T.surface, borderWidth: 1, borderColor: T.border },
  categoryActive: { backgroundColor: '#E7E7E7', borderColor: '#E7E7E7' },
  categoryText: { color: T.textSec, fontSize: 12, fontWeight: '600' },
  categoryActiveText: { color: '#111' },
  startBlock: { padding: 20 },
  sectionLabel: { marginTop: 10, marginBottom: 10, fontSize: 13, fontWeight: '800', color: T.text },
  tagWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 4 },
  tag: { maxWidth: '100%', borderRadius: 15, paddingHorizontal: 12, height: 30, justifyContent: 'center', backgroundColor: T.surface, borderWidth: 1, borderColor: T.border },
  tagText: { color: T.textSec, fontSize: 12 },
  emptySmall: { color: T.textMuted, fontSize: 12, marginBottom: 8 },
  infoCard: { marginTop: 22, borderRadius: 18, padding: 15, backgroundColor: T.surface, borderWidth: 1, borderColor: T.border },
  aiCard: { borderRadius: 19, backgroundColor: '#181818', borderWidth: 1, borderColor: '#333', padding: 16, marginBottom: 8 },
  aiTitle: { color: T.text, fontSize: 17, fontWeight: '900' },
  aiText: { marginTop: 6, color: T.textSec, fontSize: 12, lineHeight: 19 },
  aiButton: { alignSelf: 'flex-start', marginTop: 12, height: 34, paddingHorizontal: 14, borderRadius: 17, backgroundColor: '#E7E7E7', justifyContent: 'center' },
  aiButtonText: { color: '#111', fontWeight: '800', fontSize: 12 },
  discoverGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  discoverCard: { width: '31.2%', minHeight: 66, borderRadius: 15, backgroundColor: T.surface, borderWidth: 1, borderColor: T.border, padding: 10, justifyContent: 'space-between' },
  discoverTitle: { color: T.text, fontSize: 13, fontWeight: '800' },
  discoverSub: { color: T.textMuted, fontSize: 9 },
  recommendGroup: { marginTop: 18, marginHorizontal: -20, paddingLeft: 20 },
  groupHeader: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', paddingRight: 20 },
  groupTitle: { fontSize: 13, fontWeight: '800', color: T.text, marginBottom: 10 },
  groupSource: { color: T.textMuted, fontSize: 10 },
  recCard: { width: 94 },
  recCover: { width: 94, height: 132, borderRadius: 11, backgroundColor: '#222', overflow: 'hidden' },
  recTitle: { marginTop: 6, color: T.text, fontSize: 11, fontWeight: '700', lineHeight: 15 },
  recMeta: { marginTop: 2, fontSize: 9, color: T.textMuted },
  popularSource: { color: T.textMuted, fontSize: 10 },
  popularCard: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#1F1F1F' },
  popularRank: { width: 22, fontSize: 16, fontWeight: '900', color: '#BDBDBD' },
  infoTitle: { color: T.text, fontSize: 14, fontWeight: '700' },
  infoText: { marginTop: 7, color: T.textMuted, fontSize: 12, lineHeight: 19 },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  loadingText: { color: T.textMuted, fontSize: 12 },
  results: { padding: 16, paddingBottom: 34, gap: 10 },
  resultCard: { flexDirection: 'row', gap: 12, borderRadius: 18, backgroundColor: T.surface, borderWidth: 1, borderColor: T.border, padding: 11 },
  coverBox: { width: 66, height: 90, borderRadius: 11, backgroundColor: '#222', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  coverImage: { width: '100%', height: '100%' },
  resultBody: { flex: 1, minWidth: 0 },
  title: { color: T.text, fontSize: 15, fontWeight: '800', lineHeight: 20 },
  author: { marginTop: 3, color: T.textSec, fontSize: 12 },
  source: { marginTop: 3, color: T.textMuted, fontSize: 10 },
  description: { marginTop: 6, color: '#BDBDBD', fontSize: 12, lineHeight: 17 },
  readable: { alignSelf: 'flex-start', marginTop: 7, borderRadius: 9, backgroundColor: '#E7E7E7', paddingHorizontal: 7, height: 18, lineHeight: 18, color: '#111', fontSize: 10, fontWeight: '700', overflow: 'hidden' },
  noResult: { marginTop: 40, textAlign: 'center', color: T.textMuted },
  notice: {
    position: 'absolute', left: 24, right: 24, bottom: 28,
    borderRadius: 18, backgroundColor: '#1F1F1FEE', borderWidth: 1, borderColor: T.borderLight,
    paddingHorizontal: 14, paddingVertical: 11,
  },
  noticeText: { color: T.text, fontSize: 12, textAlign: 'center', lineHeight: 18 },
});
