import { StyleSheet, StatusBar } from 'react-native';
import { T } from '../lib/theme';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: T.bg },
  center: { flex: 1, backgroundColor: T.bg, alignItems: 'center', justifyContent: 'center', gap: 12 },
  topBar: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingHorizontal: 15, paddingTop: (StatusBar.currentHeight || 44) + 4, paddingBottom: 9,
    borderBottomWidth: 1,
  },
  iconButton: { width: 36, height: 36, borderRadius: 16, backgroundColor: T.surface, borderWidth: 1, borderColor: T.border, alignItems: 'center', justifyContent: 'center' },
  topTitle: { fontSize: 14, fontWeight: '800', color: T.text },
  pageInfo: { fontSize: 10, color: T.textMuted, marginTop: 1 },
  fontLabel: { fontSize: 11, fontWeight: '900', color: T.text },
  readerBody: { padding: 24, paddingBottom: 60 },
  chapterTitle: { marginBottom: 20, lineHeight: 32, fontWeight: '900', color: T.text },
  body: { lineHeight: 34, color: T.text, letterSpacing: 0.2 },
  bottomBar: {
    flexDirection: 'row', alignItems: 'center', gap: 11,
    paddingHorizontal: 13, paddingTop: 9, paddingBottom: 22,
    backgroundColor: T.surface, borderTopWidth: 1, borderTopColor: T.border,
  },
  navButton: { flexDirection: 'row', alignItems: 'center', gap: 3, height: 35, borderRadius: 16, paddingHorizontal: 11, backgroundColor: T.surface, borderWidth: 1, borderColor: T.border },
  navText: { color: T.text, fontSize: 11, fontWeight: '700' },
  disabled: { opacity: 0.4 },
  progressTrack: { flex: 1, height: 3, borderRadius: 2, backgroundColor: T.surface2 },
  progressFill: { height: 3, borderRadius: 2, backgroundColor: T.text },
  error: { color: T.textMuted, fontSize: 13, textAlign: 'center' },
  settingsPanel: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 10, borderTopWidth: 1 },
  settingLabel: { fontSize: 11, marginBottom: 8 },
  themeRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  themeButton: { flex: 1, height: 34, borderRadius: 16, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  fontRow: { flexDirection: 'row', gap: 8, paddingBottom: 4 },
  fontButton: { width: 38, height: 32, borderRadius: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  toolbarActions: { flexDirection: 'row', gap: 6 },
  toolButton: { width: 30, height: 30, borderRadius: 12, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  searchBarWrap: { paddingHorizontal: 14, paddingVertical: 8, borderBottomWidth: 1 },
  searchInput: { height: 34, borderRadius: 16, borderWidth: 1, paddingHorizontal: 12, fontSize: 13 },
  searchChip: { maxWidth: 220, borderRadius: 12, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 5 },
});
