import { StyleSheet, StatusBar } from 'react-native';
import { T } from '../lib/theme';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: T.bg },
  topBar: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    paddingHorizontal: 16, paddingTop: (StatusBar.currentHeight || 44) + 5, paddingBottom: 10,
    borderBottomWidth: 1, borderBottomColor: '#1F1F1F',
  },
  backButton: { width: 37, height: 37, borderRadius: 19, backgroundColor: T.card, borderWidth: 1, borderColor: T.border, alignItems: 'center', justifyContent: 'center' },
  topTitle: { flex: 1, textAlign: 'center', fontSize: 15, fontWeight: '800', color: T.text },
  content: { padding: 18, paddingBottom: 40 },
  sectionCard: { borderRadius: 18, backgroundColor: T.surface, borderWidth: 1, borderColor: T.border, padding: 16 },
  sectionTitle: { color: T.text, fontSize: 16, fontWeight: '900' },
  hint: { marginTop: 6, color: T.textMuted, fontSize: 11, lineHeight: 17 },
  fieldLabel: { marginTop: 14, marginBottom: 6, color: T.textSec, fontSize: 12, fontWeight: '700' },
  input: {
    minHeight: 42, maxHeight: 100, borderRadius: 12, backgroundColor: '#111',
    borderWidth: 1, borderColor: T.borderLight, paddingHorizontal: 13,
    color: T.text, fontSize: 14, textAlignVertical: 'center',
  },
  primaryButton: { height: 46, marginTop: 20, borderRadius: 23, backgroundColor: '#EDEDED', alignItems: 'center', justifyContent: 'center' },
  primaryText: { color: '#111', fontSize: 14, fontWeight: '900' },
  secondaryButton: { height: 41, marginTop: 9, borderRadius: 21, backgroundColor: T.surface, borderWidth: 1, borderColor: T.borderLight, alignItems: 'center', justifyContent: 'center' },
  secondaryText: { color: T.text, fontSize: 13, fontWeight: '700' },
  disabled: { opacity: 0.55 },
  toast: { marginTop: 12, borderRadius: 15, backgroundColor: '#222', borderWidth: 1, borderColor: T.borderLight, paddingVertical: 10, paddingHorizontal: 14 },
  toastText: { color: T.text, textAlign: 'center', fontSize: 12 },
  aboutCard: { marginTop: 22, borderRadius: 18, backgroundColor: T.surface, borderWidth: 1, borderColor: T.border, padding: 15 },
  menuGrid: { flexDirection: 'row', gap: 10, marginTop: 16 },
  menuButton: { flex: 1, borderRadius: 17, backgroundColor: T.surface, borderWidth: 1, borderColor: T.border, padding: 14 },
  menuTitle: { color: T.text, fontSize: 14, fontWeight: '800' },
  menuDesc: { marginTop: 5, color: T.textMuted, fontSize: 11 },
  aboutTitle: { color: T.text, fontSize: 14, fontWeight: '800' },
  aboutText: { marginTop: 7, color: T.textMuted, fontSize: 12, lineHeight: 19 },
  speedRow: { flexDirection: 'row', gap: 7, marginTop: 10, flexWrap: 'wrap' },
  speedButton: { width: 48, height: 34, borderRadius: 17, borderWidth: 1, borderColor: T.borderLight, alignItems: 'center', justifyContent: 'center' },
  speedActive: { backgroundColor: '#E7E7E7', borderColor: '#E7E7E7' },
  speedText: { color: T.textSec, fontSize: 11 },
  speedActiveText: { color: '#111', fontWeight: '800' },
  dangerButton: { height: 40, marginTop: 10, borderRadius: 20, backgroundColor: '#2A1515', borderWidth: 1, borderColor: '#4A2020', alignItems: 'center', justifyContent: 'center' },
  dangerText: { color: '#D6A0A0', fontSize: 13, fontWeight: '700' },
  confirmRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12 },
  confirmText: { flex: 1, color: T.textSec, fontSize: 11 },
  confirmYes: { height: 30, borderRadius: 15, paddingHorizontal: 12, justifyContent: 'center', backgroundColor: '#3A1515' },
  confirmYesText: { color: '#D6A0A0', fontSize: 11, fontWeight: '700' },
  confirmNo: { height: 30, borderRadius: 15, paddingHorizontal: 12, justifyContent: 'center', backgroundColor: T.card, borderWidth: 1, borderColor: T.border },
  confirmNoText: { color: T.textMuted, fontSize: 11 },
});

// Provider styles
const providerStyles = {
  providerOption: { flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: 12, borderWidth: 1, borderColor: T.border, marginTop: 8 },
  providerActive: { borderColor: '#FFF', backgroundColor: T.surface },
  providerRadio: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: T.borderLight, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  radioDot: { width: 10, height: 10, borderRadius: 5 },
  radioActive: { backgroundColor: '#FFF' },
  providerLabel: { color: T.text, fontSize: 14, fontWeight: '700' },
  providerDesc: { color: T.textMuted, fontSize: 11, marginTop: 2 },
};
