import { StyleSheet, StatusBar } from 'react-native';
import { T } from '../lib/theme';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: T.bg },
  topBar: {
    flexDirection: 'row', alignItems: 'center', gap: 9,
    paddingHorizontal: 16, paddingTop: (StatusBar.currentHeight || 44) + 5, paddingBottom: 12,
    borderBottomWidth: 1, borderBottomColor: T.border,
  },
  backButton: { width: 37, height: 37, borderRadius: 20, backgroundColor: T.card, borderWidth: 1, borderColor: T.border, alignItems: 'center', justifyContent: 'center' },
  topTitle: { flex: 1, fontSize: 19, fontWeight: '900', color: T.text },
  importButton: { height: 34, borderRadius: 16, paddingHorizontal: 11, justifyContent: 'center', backgroundColor: T.card, borderWidth: 1, borderColor: T.borderLight },
  importText: { color: T.textSec, fontSize: 11, fontWeight: '700' },
  tabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, padding: 15 },
  tabChip: { minHeight: 30, borderRadius: 12, paddingHorizontal: 11, justifyContent: 'center', backgroundColor: T.surface, borderWidth: 1, borderColor: T.border },
  activeTab: { backgroundColor: T.borderLight, borderColor: T.borderLight },
  tabText: { color: T.textSec, fontSize: 12 },
  activeTabText: { color: '#111', fontWeight: '800' },
  notice: { textAlign: 'center', marginBottom: 8, color: T.textMuted, fontSize: 12 },
  list: { padding: 16, paddingBottom: 30, gap: 10 },
  card: { borderRadius: 16, backgroundColor: T.surface, borderWidth: 1, borderColor: T.border, padding: 11 },
  cover: { width: 54, height: 76, borderRadius: 12, backgroundColor: T.surface2, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  coverImage: { width: '100%', height: '100%' },
  body: { flex: 1, minWidth: 0 },
  title: { color: T.text, fontSize: 14, fontWeight: '800', lineHeight: 19 },
  meta: { marginTop: 4, fontSize: 11, color: T.textMuted },
  status: { marginTop: 6, fontSize: 10, color: T.text },
  actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 7, marginTop: 10 },
  miniButton: { height: 27, borderRadius: 12, paddingHorizontal: 10, justifyContent: 'center', backgroundColor: T.surface2, borderWidth: 1, borderColor: T.border },
  danger: { borderColor: T.border },
  miniText: { color: T.textSec, fontSize: 10 },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10 },
  emptyText: { color: T.textMuted, fontSize: 13 },
});
