import { StyleSheet, StatusBar } from 'react-native';
import { T } from '../lib/theme';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: T.bg },
  topBar: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingHorizontal: 16, paddingTop: (StatusBar.currentHeight || 44) + 5, paddingBottom: 10,
    borderBottomWidth: 1, borderBottomColor: '#1F1F1F',
  },
  back: { width: 37, height: 37, borderRadius: 19, backgroundColor: T.card, borderWidth: 1, borderColor: T.border, alignItems: 'center', justifyContent: 'center' },
  title: { flex: 1, fontSize: 17, fontWeight: '900', color: T.text },
  addButton: { height: 33, borderRadius: 17, paddingHorizontal: 13, justifyContent: 'center', backgroundColor: '#E7E7E7' },
  addText: { color: '#111', fontWeight: '800', fontSize: 12 },
  notice: { marginTop: 10, textAlign: 'center', color: T.textMuted },
  list: { padding: 16, paddingBottom: 30, gap: 9 },
  card: { flexDirection: 'row', alignItems: 'center', gap: 10, borderRadius: 16, backgroundColor: T.surface, borderWidth: 1, borderColor: T.border, padding: 13 },
  name: { color: T.text, fontSize: 14, fontWeight: '700' },
  detail: { marginTop: 4, color: T.textMuted, fontSize: 11 },
  remove: { color: '#D6D6D6', fontSize: 12, fontWeight: '700' },
  customActions: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  edit: { color: '#BDBDBD', fontSize: 12 },
  modalOverlay: { flex: 1, backgroundColor: '#000000AA', justifyContent: 'center', padding: 18 },
  editorCard: { maxHeight: '85%', borderRadius: 20, backgroundColor: '#161616', borderWidth: 1, borderColor: '#2A2A2A', padding: 16 },
  editorTitle: { color: T.text, fontSize: 16, fontWeight: '900', marginBottom: 12 },
  fieldLabel: { marginTop: 12, marginBottom: 6, color: T.textSec, fontSize: 12, fontWeight: '700' },
  input: { minHeight: 40, borderRadius: 12, backgroundColor: '#0E0E0E', borderWidth: 1, borderColor: '#2A2A2A', paddingHorizontal: 12, color: T.text, fontSize: 14 },
  inputUrl: { minHeight: 44, maxHeight: 110, borderRadius: 12, backgroundColor: '#0E0E0E', borderWidth: 1, borderColor: '#2A2A2A', paddingHorizontal: 12, color: T.text, fontSize: 13, textAlignVertical: 'top' },
  kindRow: { flexDirection: 'row', gap: 8 },
  kindButton: { minHeight: 34, borderRadius: 17, paddingHorizontal: 14, justifyContent: 'center', backgroundColor: '#0E0E0E', borderWidth: 1, borderColor: '#2A2A2A' },
  kindActive: { backgroundColor: '#E7E7E7', borderColor: '#E7E7E7' },
  kindText: { color: T.textSec, fontSize: 12, fontWeight: '700' },
  kindActiveText: { color: '#111' },
  editorButtons: { flexDirection: 'row', gap: 10, marginTop: 18 },
  cancelButton: { flex: 1, height: 42, borderRadius: 21, backgroundColor: '#222', borderWidth: 1, borderColor: '#333', alignItems: 'center', justifyContent: 'center' },
  cancelText: { color: T.textSec, fontSize: 13, fontWeight: '700' },
  saveButton: { flex: 1, height: 42, borderRadius: 21, backgroundColor: '#E7E7E7', alignItems: 'center', justifyContent: 'center' },
  saveText: { color: '#111', fontSize: 13, fontWeight: '800' },
  urlBar: { flexDirection: 'row', gap: 8, marginBottom: 10, alignItems: 'center' },
  urlInput: { flex: 1, minHeight: 38, maxHeight: 80, borderRadius: 19, backgroundColor: '#0E0E0E', borderWidth: 1, borderColor: '#2A2A2A', paddingHorizontal: 13, color: T.text, fontSize: 12 },
  urlButton: { height: 38, borderRadius: 19, paddingHorizontal: 14, backgroundColor: '#E7E7E7', alignItems: 'center', justifyContent: 'center' },
  urlButtonText: { color: '#111', fontSize: 12, fontWeight: '800' },
  disabled: { opacity: 0.5 },
});
