import { StyleSheet, StatusBar } from 'react-native';
import { T } from '../lib/theme';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: T.bg },
  topBar: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingHorizontal: 16, paddingTop: (StatusBar.currentHeight || 44) + 5, paddingBottom: 10,
    borderBottomWidth: 1, borderBottomColor: T.border,
  },
  back: { width: 37, height: 37, borderRadius: 20, backgroundColor: T.card, borderWidth: 1, borderColor: T.border, alignItems: 'center', justifyContent: 'center' },
  title: { flex: 1, fontSize: 17, fontWeight: '900', color: T.text },
  addButton: { height: 33, borderRadius: 16, paddingHorizontal: 13, justifyContent: 'center', backgroundColor: T.white },
  addText: { color: T.black, fontWeight: '800', fontSize: 12 },
  notice: { marginTop: 10, textAlign: 'center', color: T.textMuted },
  list: { padding: 16, paddingBottom: 30, gap: 9 },
  card: { flexDirection: 'row', alignItems: 'center', gap: 10, borderRadius: 16, backgroundColor: T.surface, borderWidth: 1, borderColor: T.border, padding: 13 },
  name: { color: T.text, fontSize: 14, fontWeight: '700' },
  detail: { marginTop: 4, color: T.textMuted, fontSize: 11 },
  remove: { color: T.text, fontSize: 12, fontWeight: '700' },
  customActions: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  edit: { color: T.grey, fontSize: 12 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', padding: 18 },
  editorCard: { maxHeight: '85%', borderRadius: 20, backgroundColor: T.surface, borderWidth: 1, borderColor: T.border, padding: 16 },
  editorTitle: { color: T.text, fontSize: 16, fontWeight: '900', marginBottom: 12 },
  fieldLabel: { marginTop: 12, marginBottom: 6, color: T.textSec, fontSize: 12, fontWeight: '700' },
  input: { minHeight: 40, borderRadius: 12, backgroundColor: T.surface2, borderWidth: 1, borderColor: T.border, paddingHorizontal: 12, color: T.text, fontSize: 14 },
  inputUrl: { minHeight: 44, maxHeight: 110, borderRadius: 12, backgroundColor: T.surface2, borderWidth: 1, borderColor: T.border, paddingHorizontal: 12, color: T.text, fontSize: 13, textAlignVertical: 'top' },
  kindRow: { flexDirection: 'row', gap: 8 },
  kindButton: { minHeight: 34, borderRadius: 16, paddingHorizontal: 14, justifyContent: 'center', backgroundColor: T.surface2, borderWidth: 1, borderColor: T.border },
  kindActive: { backgroundColor: T.white, borderColor: T.borderLight },
  kindText: { color: T.textSec, fontSize: 12, fontWeight: '700' },
  kindActiveText: { color: T.black },
  editorButtons: { flexDirection: 'row', gap: 10, marginTop: 18 },
  cancelButton: { flex: 1, height: 42, borderRadius: 20, backgroundColor: T.surface2, borderWidth: 1, borderColor: T.border, alignItems: 'center', justifyContent: 'center' },
  cancelText: { color: T.textSec, fontSize: 13, fontWeight: '700' },
  saveButton: { flex: 1, height: 42, borderRadius: 20, backgroundColor: T.white, alignItems: 'center', justifyContent: 'center' },
  saveText: { color: T.black, fontSize: 13, fontWeight: '800' },
  urlBar: { flexDirection: 'row', gap: 8, marginBottom: 10, alignItems: 'center' },
  urlInput: { flex: 1, minHeight: 38, maxHeight: 80, borderRadius: 20, backgroundColor: T.surface2, borderWidth: 1, borderColor: T.border, paddingHorizontal: 13, color: T.text, fontSize: 12 },
  urlButton: { height: 38, borderRadius: 20, paddingHorizontal: 14, backgroundColor: T.white, alignItems: 'center', justifyContent: 'center' },
  urlButtonText: { color: T.black, fontSize: 12, fontWeight: '800' },
  disabled: { opacity: 0.5 },
  templateRow: { marginTop: 2, marginBottom: 6 },
  templateText: { color: T.textMuted, fontSize: 11, textDecorationLine: 'underline' },
});
